phyla_caracteristicas = {
    "protozoa": {
        "nivel_organizacion": "unicelular",
        "simetria": "variada",
        "capas_germinales": "ninguna",
        "cavidad_corporal": "ausente",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "ausente",
        "sistema_nervioso": "ausente",
        "sistema_corporal": "ausente",
        "reproduccion": "asexual o sexual",
        "habitat": "acuatico o parasito",
    },
    "porifera": {
        "nivel_organizacion": "multicelular",
        "simetria": "ninguna",
        "capas_germinales": "ninguna",
        "cavidad_corporal": "ausente",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "ausente",
        "sistema_nervioso": "ausente",
        "sistema_corporal": "hidrostatico",
        "reproduccion": "asexual",
        "habitat": "acuatico",
    },
    "cnidaria": {
        "nivel_organizacion": "tejidos",
        "simetria": "radial",
        "capas_germinales": "diploblastico",
        "cavidad_corporal": "ninguna",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "incompleto",
        "sistema_nervioso": "difuso",
        "sistema_corporal": "hidrostatico",
        "reproduccion": "sexual",
        "habitat": "acuatico",
    },
    "ctenophora": {
        "nivel_organizacion": "tejidos",
        "simetria": "radial",
        "capas_germinales": "diploblastico",
        "cavidad_corporal": "ninguna",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "difuso",
        "sistema_corporal": "hidrostatico",
        "reproduccion": "sexual",
        "habitat": "acuatico",
    },
    "platyhelminthes": {
        "nivel_organizacion": "organos",
        "simetria": "bilateral",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "acelomado",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "incompleto",
        "sistema_nervioso": "ganglionar",
        "sistema_corporal": "hidrostatico",
        "reproduccion": "sexual",
        "habitat": "acuatico o parasito",
    },
    "annelida": {
        "nivel_organizacion": "organos",
        "simetria": "bilateral",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "celomado",
        "segmentacion": "segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "ganglionar",
        "sistema_corporal": "hidrostatico",
        "reproduccion": "sexual",
        "habitat": "acuatico o terrestre",
    },
    "mollusca": {
        "nivel_organizacion": "organos",
        "simetria": "bilateral",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "celomado",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "ganglionar",
        "sistema_corporal": "exoesqueleto",
        "reproduccion": "sexual",
        "habitat": "acuatico o terrestre",
    },
    "nematoda": {
        "nivel_organizacion": "organos",
        "simetria": "bilateral",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "pseudocelomado",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "ganglionar",
        "sistema_corporal": "hidrostatico",
        "reproduccion": "sexual",
        "habitat": "acuatico o parasito",
    },
    "arthropoda": {
        "nivel_organizacion": "organos",
        "simetria": "bilateral",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "celomado",
        "segmentacion": "segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "ganglionar",
        "sistema_corporal": "exoesqueleto",
        "reproduccion": "sexual",
        "habitat": "acuatico o terrestre",
    },
    "echinodermata": {
        "nivel_organizacion": "organos",
        "simetria": "radial",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "celomado",
        "segmentacion": "no segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "difuso",
        "sistema_corporal": "endoesqueleto",
        "reproduccion": "sexual",
        "habitat": "acuatico",
    },
    "chordata": {
        "nivel_organizacion": "sistemas",
        "simetria": "bilateral",
        "capas_germinales": "triploblastico",
        "cavidad_corporal": "celomado",
        "segmentacion": "segmentado",
        "sistema_digestivo": "completo",
        "sistema_nervioso": "centralizado",
        "sistema_corporal": "endoesqueleto",
        "reproduccion": "sexual",
        "habitat": "acuatico, terrestre o aereo",
    },
}
