diccionario_de_referencia = {
    'Phylum': "un filo",
    'descripcion': 'una descripcion',
    'tejido': 0,
    'organos': 0,
    'sistemas': 0,
    'simetria_radial': 0,
    'simetria_bilateral': 0,
    'diploblastico': 0,
    'triploblastico': 0,
    'segmentacion': 0,
    'seudocelomados': 0,
    'celomados': 0,
    'sis_digetivo_incompleto': 0,
    'sis_digestivo_completo': 0,
    'sis_nervioso_difuso': 0,
    'sis_nervioso_ganglionar': 0,
    'sis_nervioso_central': 0,
    'endoesqueleto': 0,
    'exoesqueleto': 0,
    'hidrostatico': 0,
    'rep_sexual': 0,
    'rep_asexual': 0,
    'habitat_terrestre': 0,
    'habitat_acuatico': 0,
    'parasitario': 0
}
